name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Load cache for python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --requirement requirements-dev.txt
      - name: Run Anki Add-on Builder
        run: |
          aab build -d local
      - name: Save built addon
        uses: actions/upload-artifact@v3
        with:
          name: ankiaddon
          path: build/*.ankiaddon
          if-no-files-found: error
